[package]
name = "rustysd"
version = "0.1.0"
authors = ["Moritz Borcherding <moritz.borcherding@web.de>"]
edition = "2018"

[dependencies]
signal-hook = "0.1.10"
libc = "0.2.65"
nix = "0.6.0"
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.9"

